name: Sierra
version: '1.0.0'
author: Feelix
main: de.feelix.sierra.Sierra
description: Packet Analysis Tool for the Minecraft Protocol
website: https://discord.gg/squarecode
api-version: 1.13
softdepend:
  - packetevents
commands:
  sierra:
    description: Main command of the system
permissions:
  sierra.command:
    description: General permission for the main command
    default: op