name: Sierra
version: '1.4.9'
author: Feelix
main: de.feelix.sierra.Sierra
description: Packet Analysis Tool for the Minecraft Protocol
website: https://discord.gg/squarecode
folia-supported: true
api-version: 1.13
softdepend:
  - packetevents
commands:
  sierra:
    description: Main command of the system
permissions:
  sierra.bypass:
    description: Bypass permission for the checks. Need to be enabled in the config
    default: false
  sierra.update:
    description: Show update notification
    default: op
  sierra.command:
    description: General permission for the main command
    default: op
  sierra.command.info:
    description: Permission for the info sub-command
    default: op
  sierra.command.monitor:
    description: Permission for the monitor sub-command
    default: op
  sierra.command.alerts:
    description: Permission for the alerts sub-command
    default: op
  sierra.command.history:
    description: Permission for the history sub-command
    default: op
  sierra.command.reload:
    description: Permission for the reload sub-command
    default: op
  sierra.*:
    default: false
    description: Admin permission for sierra
    children:
      - sierra.command.*
      - sierra.update
  sierra.command.*:
    description: Permission for all sub-commands
    default: false
    children:
      - sierra.command.monitor
      - sierra.command.alerts
      - sierra.command.history
      - sierra.command.info
      - sierra.command.reload
      - sierra.command