name: Sierra
version: '1.2.3'
author: Feelix
main: de.feelix.sierra.Sierra
description: Packet Analysis Tool for the Minecraft Protocol
website: https://discord.gg/squarecode
folia-supported: true
api-version: 1.13
softdepend:
  - packetevents
commands:
  sierra:
    description: Main command of the system
permissions:
  sierra.update:
    description: Show update notification
    default: op
  sierra.command:
    description: General permission for the main command
    default: op